# Generated by Django 4.2.13 on 2024-07-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_catagory',
            name='Image',
            field=models.ImageField(default='pexels-alexander-pollinger-137430820-105668981.jpg', upload_to='carImages/'),
        ),
    ]
