# Generated by Django 4.2.13 on 2024-07-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_vehicle_catagory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_type',
            name='Image',
            field=models.ImageField(default='', upload_to='carImages/'),
        ),
    ]
